#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 09:56:12 2017

@author: RebecaMoreno
"""





import random as rdm

x = 0
while x = 0:
  opcao = input('escolha: dormir ou passear?')
  if opcao == 'dormir':
    print('Boa noite')
    x = 1
    
  else:
    inimigo = rdm.randint()