#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 09:56:12 2017

@author: RebecaMoreno
"""





import random as rdm
import json

with open('pokedex.json',"r") as arquivo: 
    pokedex = json.load(arquivo)
    #print(pokedex[-1])
posicaoi = rdm.randint(0,13)
print(pokedex[posicaoi])


#organizar melhor
#Abrir o arquivo
#Lopping infinito
#if e else(do looping)    
#dormir
#passear
#encontrar ou nao o bicho
#lutar ou correr
#morrer ou nao


    
x = 0
while x == 0:
  opcao = input('escolha: dormir ou passear?')
  if opcao == 'dormir':
    print('Boa noite')
    x = 1
    
  else:
    posicaoi = rdm.randint(0,13)
    print(pokedex[posicaoi])
#comentario
